
---
deployment:
  tasks:
    - export DEPLOYPATH=/public_html/website_e561caa2
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R PHPMailer $DEPLOYPATH
    - /bin/cp  contact_form_submit.php $DEPLOYPATH
    - /bin/cp  index.html $DEPLOYPATH