
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/sazxjwte/public_html/website_e561caa2/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp  index.html $DEPLOYPATH